### PR TITLE
Fix crash when source length is not aligned

### PR DESCRIPTION
**Pull request by ayufan**
This happens, because total_length is 0 and we start writing out of buffer and this results in crash later.

### CODE REVIEW

**Comment by longsleep** [comment]
This adds a bunch of .o binary files below update_toc0/main - is that intentional? Also do you have details where the updated implementations come from?

**Comment by ayufan** [comment]
Nope, sorry

**Comment by ayufan** [comment]
I'm working on a new changeset that adds that from lichee-dev-3.0

**Comment by ayufan** [comment]
Updated with info, and also removed object files

**Pull request merged**
